name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 94889e59a7dc8091c75b5425e0665194
          TIMEZONE: Asia/Ho_Chi_Minh
          K_FORMAT: true
          ALL_COMMITS: true
